test if login was successfull

diff --git a/etc/init.d/docker-credential-file b/etc/init.d/docker-credential-file
--- a/etc/init.d/docker-credential-file
+++ b/etc/init.d/docker-credential-file
@@ -17,6 +17,15 @@ start() {
     if [ $status -eq 0 ]; then
         base64 -d /tmp/docker-credential-file.encoded > /tmp/docker-credential-file
         sudo --user buildkite docker login --username _json_key --password "$(cat /tmp/docker-credential-file)" https://eu.gcr.io
+        # check if ~/.docker/config.json exists
+        if [ ! -f "/home/buildkite/.docker/config.json" ]; then
+            echo "Failed because /home/buildkite/.docker/config.json does not exist"
+            exit 1
+        fi
+        if [ $(cat /home/buildkite/.docker/config.json | grep '"auth"' | wc -l) != "1" ]; then
+            echo "Failed because /home/buildkite/.docker/config.json is not logged in"
+            exit 1  
+        fi
     fi
     rm -rf /tmp/docker-credential-file.encoded
 }
